In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../GSE64881_segmentation_at_30000bp.passqc.multibam.txt",sep="\t")

In [3]:
df.head()

,chrom,start,stop,F10A2,F10A3,F10A4,F10A5,F10A6,F10B1,F10B2,...,F9F2,F9F3,F9F4,F9F5,F9F6,F9G1,F9G2,F9G3,F9G4,F9G5
0,chr1,0,30000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,chr1,30000,60000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,chr1,60000,90000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,chr1,90000,120000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,chr1,120000,150000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
def my_index(df):
	return df['chrom'] + ":" + df['start'].astype(str) + "-" + df['stop'].astype(str)

In [5]:
df.index = my_index(df)

In [6]:
df.head()

,chrom,start,stop,F10A2,F10A3,F10A4,F10A5,F10A6,F10B1,F10B2,...,F9F2,F9F3,F9F4,F9F5,F9F6,F9G1,F9G2,F9G3,F9G4,F9G5
chr1:0-30000,chr1,0,30000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
chr1:30000-60000,chr1,30000,60000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
chr1:60000-90000,chr1,60000,90000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
chr1:90000-120000,chr1,90000,120000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
chr1:120000-150000,chr1,120000,150000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
df = df.drop(['chrom','start','stop'],axis=1)
df.head()

,F10A2,F10A3,F10A4,F10A5,F10A6,F10B1,F10B2,F10B3,F10B4,F10B5,...,F9F2,F9F3,F9F4,F9F5,F9F6,F9G1,F9G2,F9G3,F9G4,F9G5
chr1:0-30000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
chr1:30000-60000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
chr1:60000-90000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
chr1:90000-120000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
chr1:120000-150000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
df.describe()

,F10A2,F10A3,F10A4,F10A5,F10A6,F10B1,F10B2,F10B3,F10B4,F10B5,...,F9F2,F9F3,F9F4,F9F5,F9F6,F9G1,F9G2,F9G3,F9G4,F9G5
count,90877.000000,90877.000000,90877.000000,90877.000000,90877.000000,90877.000000,90877.000000,90877.000000,90877.000000,90877.000000,...,90877.000000,90877.000000,90877.000000,90877.000000,90877.000000,90877.000000,90877.000000,90877.000000,90877.000000,90877.000000
mean,0.064670,0.083255,0.054447,0.042156,0.009199,0.003180,0.091090,0.071173,0.049859,0.065110,...,0.095602,0.066750,0.036665,0.002784,0.023152,0.026046,0.039174,0.037699,0.022393,0.062172
std,0.245944,0.276269,0.226899,0.200946,0.095471,0.056303,0.287739,0.257115,0.217654,0.246721,...,0.294046,0.249589,0.187939,0.052690,0.150387,0.159274,0.194009,0.190469,0.147958,0.241469
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
gam = pd.read_csv("SLICE_02.chromatin_interaction_pairs_of_features.csv.gz")
gam.head()

,name,variable,value,R1-Overlap-Genes,R2-Overlap-Genes,R1-Overlap-TADs,R2-Overlap-TADs
0,chr7:96720000-96750000,chr7:96810000-96840000,1.0,NaN,Me3,chr7:96600000-97080000,chr7:96600000-97080000
1,chr7:64470000-64500000,chr7:64500000-64530000,1.0,Gabrg3,Gabrg3,chr7:64120000-64760000,chr7:64120000-64760000
2,chr7:94290000-94320000,chr7:94320000-94350000,1.0,NaN,NaN,chr7:94240000-94720000,chr7:94240000-94720000
3,chr7:126720000-126750000,chr7:126750000-126780000,1.0,"Acsm2,Acsm1","Acsm1,Acsm2",chr7:125880000-126800000,chr7:125880000-126800000
4,chr7:73080000-73110000,chr7:73110000-73140000,1.0,Pcsk6,Pcsk6,chr7:72840000-73240000,chr7:72840000-73240000

In [9]:
gam1 = gam.set_index(['name'])
gam2 = gam.set_index(['variable'])
gam1.head()

,variable,value,R1-Overlap-Genes,R2-Overlap-Genes,R1-Overlap-TADs,R2-Overlap-TADs
name,,,,,,
chr7:96720000-96750000,chr7:96810000-96840000,1.0,NaN,Me3,chr7:96600000-97080000,chr7:96600000-97080000
chr7:64470000-64500000,chr7:64500000-64530000,1.0,Gabrg3,Gabrg3,chr7:64120000-64760000,chr7:64120000-64760000
chr7:94290000-94320000,chr7:94320000-94350000,1.0,NaN,NaN,chr7:94240000-94720000,chr7:94240000-94720000
chr7:126720000-126750000,chr7:126750000-126780000,1.0,"Acsm2,Acsm1","Acsm1,Acsm2",chr7:125880000-126800000,chr7:125880000-126800000
chr7:73080000-73110000,chr7:73110000-73140000,1.0,Pcsk6,Pcsk6,chr7:72840000-73240000,chr7:72840000-73240000

In [10]:
gam1.index.names = ['locus1']
gam1.head()

,variable,value,R1-Overlap-Genes,R2-Overlap-Genes,R1-Overlap-TADs,R2-Overlap-TADs
locus1,,,,,,
chr7:96720000-96750000,chr7:96810000-96840000,1.0,NaN,Me3,chr7:96600000-97080000,chr7:96600000-97080000
chr7:64470000-64500000,chr7:64500000-64530000,1.0,Gabrg3,Gabrg3,chr7:64120000-64760000,chr7:64120000-64760000
chr7:94290000-94320000,chr7:94320000-94350000,1.0,NaN,NaN,chr7:94240000-94720000,chr7:94240000-94720000
chr7:126720000-126750000,chr7:126750000-126780000,1.0,"Acsm2,Acsm1","Acsm1,Acsm2",chr7:125880000-126800000,chr7:125880000-126800000
chr7:73080000-73110000,chr7:73110000-73140000,1.0,Pcsk6,Pcsk6,chr7:72840000-73240000,chr7:72840000-73240000

In [11]:
gam2.index.names = ['locus1']
gam2.head()

,name,value,R1-Overlap-Genes,R2-Overlap-Genes,R1-Overlap-TADs,R2-Overlap-TADs
locus1,,,,,,
chr7:96810000-96840000,chr7:96720000-96750000,1.0,NaN,Me3,chr7:96600000-97080000,chr7:96600000-97080000
chr7:64500000-64530000,chr7:64470000-64500000,1.0,Gabrg3,Gabrg3,chr7:64120000-64760000,chr7:64120000-64760000
chr7:94320000-94350000,chr7:94290000-94320000,1.0,NaN,NaN,chr7:94240000-94720000,chr7:94240000-94720000
chr7:126750000-126780000,chr7:126720000-126750000,1.0,"Acsm2,Acsm1","Acsm1,Acsm2",chr7:125880000-126800000,chr7:125880000-126800000
chr7:73110000-73140000,chr7:73080000-73110000,1.0,Pcsk6,Pcsk6,chr7:72840000-73240000,chr7:72840000-73240000

In [12]:
temp = gam1.columns.tolist()
temp[0] = 'locus2'
gam1.columns = temp
gam1.head()

,locus2,value,R1-Overlap-Genes,R2-Overlap-Genes,R1-Overlap-TADs,R2-Overlap-TADs
locus1,,,,,,
chr7:96720000-96750000,chr7:96810000-96840000,1.0,NaN,Me3,chr7:96600000-97080000,chr7:96600000-97080000
chr7:64470000-64500000,chr7:64500000-64530000,1.0,Gabrg3,Gabrg3,chr7:64120000-64760000,chr7:64120000-64760000
chr7:94290000-94320000,chr7:94320000-94350000,1.0,NaN,NaN,chr7:94240000-94720000,chr7:94240000-94720000
chr7:126720000-126750000,chr7:126750000-126780000,1.0,"Acsm2,Acsm1","Acsm1,Acsm2",chr7:125880000-126800000,chr7:125880000-126800000
chr7:73080000-73110000,chr7:73110000-73140000,1.0,Pcsk6,Pcsk6,chr7:72840000-73240000,chr7:72840000-73240000

In [13]:
temp = gam2.columns.tolist()
temp[0] = 'locus2'
gam2.columns = temp
gam2.head()

,locus2,value,R1-Overlap-Genes,R2-Overlap-Genes,R1-Overlap-TADs,R2-Overlap-TADs
locus1,,,,,,
chr7:96810000-96840000,chr7:96720000-96750000,1.0,NaN,Me3,chr7:96600000-97080000,chr7:96600000-97080000
chr7:64500000-64530000,chr7:64470000-64500000,1.0,Gabrg3,Gabrg3,chr7:64120000-64760000,chr7:64120000-64760000
chr7:94320000-94350000,chr7:94290000-94320000,1.0,NaN,NaN,chr7:94240000-94720000,chr7:94240000-94720000
chr7:126750000-126780000,chr7:126720000-126750000,1.0,"Acsm2,Acsm1","Acsm1,Acsm2",chr7:125880000-126800000,chr7:125880000-126800000
chr7:73110000-73140000,chr7:73080000-73110000,1.0,Pcsk6,Pcsk6,chr7:72840000-73240000,chr7:72840000-73240000

In [14]:
temp = gam2.columns.tolist()
new_names = []
for i in temp:
    if "R1" in i:
        new_names.append(i.replace("R1","R2"))
    elif "R2" in i:
        new_names.append(i.replace("R2","R1"))
    else:
        new_names.append(i)
gam2.columns = new_names
gam2.head()

,locus2,value,R2-Overlap-Genes,R1-Overlap-Genes,R2-Overlap-TADs,R1-Overlap-TADs
locus1,,,,,,
chr7:96810000-96840000,chr7:96720000-96750000,1.0,NaN,Me3,chr7:96600000-97080000,chr7:96600000-97080000
chr7:64500000-64530000,chr7:64470000-64500000,1.0,Gabrg3,Gabrg3,chr7:64120000-64760000,chr7:64120000-64760000
chr7:94320000-94350000,chr7:94290000-94320000,1.0,NaN,NaN,chr7:94240000-94720000,chr7:94240000-94720000
chr7:126750000-126780000,chr7:126720000-126750000,1.0,"Acsm2,Acsm1","Acsm1,Acsm2",chr7:125880000-126800000,chr7:125880000-126800000
chr7:73110000-73140000,chr7:73080000-73110000,1.0,Pcsk6,Pcsk6,chr7:72840000-73240000,chr7:72840000-73240000

In [15]:

for c in df.columns:
    print (c)
    index_list = df[df[c] == 1].index.tolist()
    res = pd.concat([gam1.loc[index_list][gam1.loc[index_list]['locus2'].notnull()],gam2.loc[index_list][gam2.loc[index_list]['locus2'].notnull()]])
    res[res.columns[::-1]].to_csv(c+".GAM02.csv")

F10A2

E:\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """

F10A3
F10A4
F10A5
F10A6
F10B1
F10B2
F10B3
F10B4
F10B5
F10B6
F10C1
F10C2
F10C3
F10C4
F10C6
F10D1
F10D2
F10D3
F10D5
F10D6
F10E1
F10E2
F10E3
F10E4
F10E5
F10E6
F10F1
F10F2
F10F3
F10F4
F10F5
F10F6
F10G1
F10G2
F10G4
F10G5
F11A1
F11A2
F11A3
F11A4
F11A5
F11A6
F11B1
F11B2
F11B3
F11B4
F11B5
F11C1
F11C2
F11C3
F11C4
F11C6
F11D1
F11D2
F11D3
F11D4
F11D6
F11E1
F11E3
F11E4
F11E5
F11E6
F11F1
F11F2
F11F4
F11F5
F11F6
F11G1
F11G3
F11G4
F12A2
F12A4
F12A6
F12B1
F12B2
F12B3
F12B5
F12B6
F12C1
F12C2
F12C4
F12C6
F12D4
F12D5
F12D6
F12E1
F12E3
F12E4
F12E5
F12E6
F12F1
F12F2
F12F4
F12F5
F12F6
F12G1
F12G2
F12G3
F12G4
F15A3
F15A5
F15A6
F15A7
F15A8
F15B1
F15B3
F15B4
F15B5
F15B6
F15B7
F15B8
F15C1
F15C2
F15C3
F15C4
F15C5
F15C6
F15C7
F15C8
F15D1
F15D2
F15D3
F15D4
F15D7
F15D8
F15E1
F15E2
F15E4
F15E5
F15E6
F15E7
F15E8
F15F1
F15F2
F15F3
F15F4
F15F5
F15F6
F15F7
F15F8
F15G1
F15G3
F15G4
F15G5
F15G6
F15G7
F15G8
F15H1
F15H5
F15H7
F16A1
F16A2
F16A3
F16A4
F16A5
F16A6
F16A7
F16B1
F16B2
F16B3
F16B4
F16B5
F16B6
F16B7
F16C1
F16C3
F16C4
F16C5
F16C6
F16C7
F16D1
F16D2
F16D3
F16D4
F16D5
F16D6
F16D7
F16E1
F16E2
F16E3
F16E4
F16E5
F16E6
F16E7
F16F1
F16F2
F16F3
F16F4
F16F5
F16F6
F16F7
F16G1
F16G3
F16G4
F16G5
F16G6
F17A1
F17A2
F17A3
F17A6
F17A7
F17B1
F17B2
F17B3
F17B6
F17B7
F17C1
F17C2
F17C3
F17C4
F17C6
F17C7
F17D1
F17D2
F17D4
F17D6
F17D7
F17E1
F17E2
F17E3
F17E4
F17E5
F17E6
F17E7
F17F1
F17F2
F17F3
F17F4
F17F5
F17F6
F17F7
F17G1
F17G3
F17G4
F17G5
F17G6
F18A1
F18B1
F18B2
F18B3
F18B4
F18C1
F18C2
F18C3
F18C4
F18D1
F18D2
F18E1
F18E2
F18E3
F18F1
F18F2
F18F3
F18F4
F18G1
F18G3
F18G4
F3F1
F5A2
F5A4
F5B1
F5B2
F5B3
F5B4
F5C1
F5C2
F5C3
F5C4
F5D1
F5D3
F5D4
F5E2
F5E3
F5E4
F5F2
F5F4
F5G2
F6A2
F6A4
F6B2
F6B3
F6B4
F6C2
F6C4
F6D2
F6D3
F6D4
F6E2
F6E3
F6E4
F6F2
F6F3
F6F4
F6G1
F6G2
F6G3
F7A1
F7A2
F7A3
F7A4
F7A5
F7A6
F7B1
F7B2
F7B3
F7B4
F7B5
F7B6
F7C1
F7C2
F7C3
F7C4
F7C5
F7C6
F7D1
F7D2
F7D3
F7D4
F7D5
F7D6
F7E1
F7E2
F7E5
F7E6
F7F1
F7F2
F7F3
F7F4
F7F5
F7F6
F7G1
F7G2
F7G3
F7G5
F8A1
F8A2
F8A3
F8A4
F8A6
F8B1
F8B2
F8B4
F8B5
F8B6
F8C1
F8C2
F8C3
F8C4
F8C5
F8C6
F8D1
F8D2
F8D3
F8D4
F8D5
F8D6
F8E1
F8E2
F8E3
F8E4
F8E6
F8F1
F8F2
F8F3
F8F4
F8G1
F8G2
F8G3
F8G4
F8G5
F9A1
F9A2
F9A3
F9A4
F9A5
F9A6
F9B1
F9B2
F9B3
F9B4
F9B5
F9B6
F9C1
F9C2
F9C4
F9C5
F9D1
F9D2
F9D3
F9D5
F9D6
F9E2
F9E3
F9E4
F9E5
F9E6
F9F1
F9F2
F9F3
F9F4
F9F5
F9F6
F9G1
F9G2
F9G3
F9G4
F9G5

In [16]:
res[res.columns[::-1]]

,value,locus2,R2-Overlap-TADs,R2-Overlap-Genes,R1-Overlap-TADs,R1-Overlap-Genes
locus1,,,,,,
chr1:21840000-21870000,0.338276,chr1:69540000-69570000,chr1:69240000-71600000,Ikzf2,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.328648,chr1:87960000-87990000,chr1:87520000-88240000,"Psmd1,SNORA26,Htr2b,2810459M11Rik",chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.304264,chr1:25200000-25230000,chr1:24280000-25960000,Bai3,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.289516,chr1:25680000-25710000,chr1:24280000-25960000,Bai3,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.288509,chr1:88170000-88200000,chr1:87520000-88240000,"Armc9,Gm16341,B3gnt7",chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.272449,chr1:70260000-70290000,chr1:69240000-71600000,Spag16,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.265453,chr1:69570000-69600000,chr1:69240000-71600000,Ikzf2,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.263680,chr1:39360000-39390000,chr1:39040000-39600000,"Npas2,Gm3617",chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.262848,chr1:39330000-39360000,chr1:39040000-39600000,"Npas2,Gm20428,Gm3617",chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.260036,chr1:126240000-126270000,NaN,NaN,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.257668,chr1:38880000-38910000,chr1:38200000-39040000,"Lonrf2,Chst10",chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.251579,chr1:88020000-88050000,chr1:87520000-88240000,"Psmd1,Armc9,Htr2b",chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.250378,chr1:88050000-88080000,chr1:87520000-88240000,"Psmd1,Armc9",chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.249878,chr1:88200000-88230000,chr1:87520000-88240000,"B3gnt7,Gm5258,Gm16341,Ncl",chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.241756,chr1:149610000-149640000,chr1:149120000-151640000,NaN,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.241043,chr1:64290000-64320000,chr1:63200000-64640000,NaN,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.236259,chr1:71640000-71670000,chr1:71600000-72280000,"Fn1,Atic",chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.235218,chr1:24630000-24660000,chr1:24280000-25960000,"Gm10925,Gm10222",chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.234184,chr1:90180000-90210000,"chr1:89040000-90200000,chr1:90200000-90640000","Trpm8,Hjurp",chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.232414,chr1:25620000-25650000,chr1:24280000-25960000,Bai3,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.232254,chr1:96690000-96720000,chr1:95720000-98720000,NaN,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.231907,chr1:137190000-137220000,chr1:137040000-137720000,"Timm17a,Lmod1,Rnpep",chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.231102,chr1:38940000-38970000,chr1:38200000-39040000,Chst10,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.230808,chr1:143520000-143550000,chr1:142600000-144640000,NaN,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.230507,chr1:113790000-113820000,chr1:113560000-114280000,NaN,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.230377,chr1:38640000-38670000,chr1:38200000-39040000,Aff3,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.229782,chr1:117360000-117390000,chr1:117160000-118400000,NaN,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.228127,chr1:71670000-71700000,chr1:71600000-72280000,"Fn1,Apol7d",chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.227753,chr1:156300000-156330000,chr1:156040000-156600000,Cacna1e,chr1:21360000-22560000,Kcnq5
chr1:21840000-21870000,0.227680,chr1:70290000-70320000,chr1:69240000-71600000,Spag16,chr1:21360000-22560000,Kcnq5
...,...,...,...,...,...,...
chr19:53280000-53310000,0.246826,chr19:14040000-14070000,chr19:14000000-16040000,NaN,chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.245392,chr19:16080000-16110000,chr19:16080000-16840000,"C130060C02Rik,Rpl37-ps1",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.244564,chr19:47280000-47310000,chr19:46680000-47920000,Neurl1a,chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.243469,chr19:34830000-34860000,chr19:34320000-34880000,"Slc16a12,U1",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.240704,chr19:12300000-12330000,chr19:12080000-13960000,"Olfr1432,Olfr262,Olfr235",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.240070,chr19:13980000-14010000,chr19:14000000-16040000,Olfr1505,chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.234718,chr19:36930000-36960000,chr19:36880000-37440000,Tnks2,chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.233658,chr19:47820000-47850000,chr19:46680000-47920000,"Wdr96,Sfr1",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.232803,chr19:12600000-12630000,chr19:12080000-13960000,"Fam111a,Gm16274",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.232296,chr19:16320000-16350000,chr19:16080000-16840000,"Gnaq,Gm10819,Gm17068",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.231953,chr19:12570000-12600000,chr19:12080000-13960000,Dtx4,chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.227367,chr19:48300000-48330000,chr19:48000000-50240000,"Sorcs3,5S_rRNA",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.220978,chr19:18570000-18600000,chr19:17480000-18920000,NaN,chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.220108,chr19:47550000-47580000,chr19:46680000-47920000,"Obfc1,Sh3pxd2a",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.220016,chr19:47130000-47160000,chr19:46680000-47920000,"U6,Taf5,Usmg5,Pcgf6,Pdcd11",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.219006,chr19:46350000-46380000,chr19:46120000-46600000,"Gbf1,Nfkb2,Psd,Gm16726",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.216812,chr19:48270000-48300000,chr19:48000000-50240000,Sorcs3,chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.214432,chr19:12510000-12540000,chr19:12080000-13960000,"Mpeg1,Dtx4,Pfpl,Olfr1441",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.213379,chr19:12450000-12480000,chr19:12080000-13960000,Olfr1440,chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.211090,chr19:33630000-33660000,chr19:33440000-34240000,Lipo1,chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.210911,chr19:48630000-48660000,chr19:48000000-50240000,Sorcs3,chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.209805,chr19:33510000-33540000,chr19:33440000-34240000,"Gm8975,Gm7237",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.207439,chr19:35010000-35040000,chr19:35000000-36160000,"Kif20b,Mir1950",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.207409,chr19:13920000-13950000,chr19:12080000-13960000,"Olfr1502,Olfr1503-ps1,Olfr1501,Olfr1504",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.206333,chr19:12930000-12960000,chr19:12080000-13960000,"Olfr1444,Olfr1445,Olfr1446,Gm5244",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.204651,chr19:16410000-16440000,chr19:16080000-16840000,Gnaq,chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.202694,chr19:44070000-44100000,NaN,"Cyp2c44,Cpn1,Erlin1",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.202568,chr19:46650000-46680000,NaN,"Sfxn2,D19Wsu162e,Arl3",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.202545,chr19:16470000-16500000,chr19:16080000-16840000,"Gnaq,Gna14",chr19:53080000-53680000,Add3
chr19:53280000-53310000,0.200966,chr19:33720000-33750000,chr19:33440000-34240000,"Lipo1,Gm8980",chr19:53080000-53680000,Add3

In [85]:
gam1['locus2'].shape

(67936,)

In [54]:

for c in df.columns:
    index_list = df[df[c] == 1].index.tolist()
    break

In [57]:
gam1.loc[index_list].dropna()

E:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.

                                          locus2     value
locus1
chr1:60960000-60990000    chr1:61050000-61080000  0.749046
chr1:60960000-60990000    chr1:61020000-61050000  0.596977
chr1:60960000-60990000    chr1:62580000-62610000  0.550861
chr1:61290000-61320000    chr1:63030000-63060000  0.599983
chr1:61290000-61320000    chr1:62460000-62490000  0.578144
chr1:61290000-61320000    chr1:62550000-62580000  0.567764
chr1:61290000-61320000    chr1:62520000-62550000  0.545250
chr1:61290000-61320000    chr1:62970000-63000000  0.505440
chr1:61290000-61320000    chr1:62910000-62940000  0.502785
chr1:61320000-61350000    chr1:61380000-61410000  0.676674
chr1:61320000-61350000    chr1:63030000-63060000  0.675093
chr1:61320000-61350000    chr1:62910000-62940000  0.649998
chr1:61320000-61350000    chr1:63000000-63030000  0.640110
chr1:61320000-61350000    chr1:62970000-63000000  0.637363
chr1:61320000-61350000    chr1:62520000-62550000  0.629116
chr1:61320000-61350000    chr1:61440000-61470000  0.571457
chr1:61320000-61350000    chr1:62850000-62880000  0.566452
chr1:61320000-61350000    chr1:62880000-62910000  0.555450
chr1:61320000-61350000    chr1:62430000-62460000  0.529480
chr1:61320000-61350000    chr1:63060000-63090000  0.528770
chr1:61320000-61350000    chr1:62760000-62790000  0.513744
chr1:61320000-61350000    chr1:62730000-62760000  0.504242
chr1:61320000-61350000    chr1:62670000-62700000  0.503685
chr1:61350000-61380000    chr1:61380000-61410000  0.982796
chr1:61350000-61380000    chr1:61440000-61470000  0.667824
chr1:61350000-61380000    chr1:61410000-61440000  0.645401
chr1:61350000-61380000    chr1:62460000-62490000  0.597649
chr1:61350000-61380000    chr1:62970000-63000000  0.579067
chr1:61350000-61380000    chr1:62070000-62100000  0.576069
chr1:61350000-61380000    chr1:62670000-62700000  0.562683
...                                          ...       ...
chr19:55890000-55920000  chr19:55950000-55980000  0.685059
chr19:55890000-55920000  chr19:56160000-56190000  0.510559
chr19:55920000-55950000  chr19:56160000-56190000  0.574032
chr19:56160000-56190000  chr19:56340000-56370000  0.612717
chr19:56160000-56190000  chr19:56250000-56280000  0.551384
chr19:56430000-56460000  chr19:57090000-57120000  0.561958
chr19:56430000-56460000  chr19:57150000-57180000  0.548382
chr19:56490000-56520000  chr19:56640000-56670000  0.571487
chr19:56490000-56520000  chr19:56910000-56940000  0.537956
chr19:56610000-56640000  chr19:60570000-60600000  0.519375
chr19:56700000-56730000  chr19:56760000-56790000  0.616844
chr19:56700000-56730000  chr19:60570000-60600000  0.509655
chr19:56700000-56730000  chr19:58890000-58920000  0.504059
chr19:56910000-56940000  chr19:57030000-57060000  0.552715
chr19:57150000-57180000  chr19:57330000-57360000  0.558708
chr19:57210000-57240000  chr19:57540000-57570000  0.666092
chr19:57270000-57300000  chr19:57300000-57330000  0.727982
chr19:57570000-57600000  chr19:58530000-58560000  0.535027
chr19:58590000-58620000  chr19:58680000-58710000  0.551384
chr19:58740000-58770000  chr19:60030000-60060000  0.541618
chr19:58800000-58830000  chr19:58830000-58860000  0.771400
chr19:58800000-58830000  chr19:59190000-59220000  0.589203
chr19:58800000-58830000  chr19:59160000-59190000  0.580795
chr19:58800000-58830000  chr19:59460000-59490000  0.561958
chr19:58800000-58830000  chr19:60030000-60060000  0.551975
chr19:58800000-58830000  chr19:60210000-60240000  0.530754
chr19:58860000-58890000  chr19:58920000-58950000  0.893188
chr19:59070000-59100000  chr19:59190000-59220000  0.510551
chr19:60210000-60240000  chr19:60270000-60300000  0.635193
chr19:60210000-60240000  chr19:60360000-60390000  0.504654

[4875 rows x 2 columns]

In [51]:
gam1[].loc['chr18:48120000-48150000']

locus2    chr18:48150000-48180000
value                           1
Name: chr18:48120000-48150000, dtype: object