In [1]:
import pandas as pd
df = pd.read_csv("test.tsv",sep="\t",header=None)

In [2]:
def get_coef(value):
    if value == 4.5:
        return 0.94
    if value == 4.9:
        return 0.99    
    if value == 4:
        return 0.89
    if value == 3.5:
        return 0.84
    if value == 3:
        return 0.79
    if value == 2.5:
        return 0.74
    if value == 2:
        return 0.69
    if value == 1.0:
        return 0.5
    if value == 5.0:
        return 1.0   

def calculate_score(l):
    
    s = l[2] + 5*get_coef(l[3])+ 5*get_coef(l[4])+ 5*get_coef(l[5])
#     print s
    return s*27.7778

In [3]:
df

              0          1  2    3    4    5
0         Allen    Abigail  3  5.0  5.0  4.5
1     Armstrong     Marcus  3  5.0  4.0  3.0
2     Bitikofer       Eric  3  3.0  3.0  3.0
3      Caggiano      Emily  3  4.0  5.0  4.0
4       Calhoun      Gyasi  3  5.0  4.5  5.0
5           Cao    Yanyang  3  4.0  4.5  3.0
6        Eaddie  Nathaneil  3  3.0  3.0  1.0
7      Erickson     Bailey  3  3.0  4.0  3.0
8        Fisher   Kimberly  3  4.0  3.0  4.5
9          Hong      Alexa  3  4.0  3.0  3.0
10        Huang      Yinan  3  4.0  4.0  5.0
11         Huff       John  3  5.0  5.0  5.0
12       Martin       Brad  3  5.0  3.5  4.0
13      McQuade      Aaron  3  4.0  4.0  4.0
14       Mullin    Maxwell  3  3.0  4.0  3.0
15     Naetzker     Hannah  3  5.0  5.0  3.0
16      O'Brien     Dakota  3  3.0  4.5  3.0
17        Scott      Chris  3  2.0  2.0  2.0
18        Steen      Kayla  3  4.0  5.0  5.0
19   Wisemiller   Danielle  3  5.0  5.0  4.9
20  Worthington     Jordan  3  5.0  4.0  5.0
21        Zhang    Yingnan  3  4.5  4.0  4.5

In [4]:
scores = []
for i in df.index:
    my_list = df.ix[i].tolist()
#     print my_list
    a = calculate_score(my_list)
    print a

491.66706
455.55592
412.50033
469.44482
491.66706
447.22258
372.22252
426.38923
447.22258
426.38923
469.44482
500.0004
462.50037
454.16703
426.38923
470.83371
433.33368
370.83363
484.72261
498.61151
484.72261
468.05593

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until